Repository nhsuk/nhsapp-frontend, pull requests merged in 2025-03, with the labels that each got.

#230 Add homepage pattern guidance
  docs/_includes/layouts/pattern.njk
  docs/examples/homepage/homepage-native.njk
  docs/examples/homepage/homepage-web.njk
  docs/patterns/homepage.md
Labels: documentation, pattern

#228 Add hub page pattern guidance
  .eleventy.js
  docs/_data/data.json
  docs/_includes/layouts/partials/bottom-nav-native.njk
  docs/_includes/layouts/partials/feedback-section.njk
  docs/_includes/layouts/pattern.njk
  docs/examples/error-pages/problem-with-service.njk
  docs/examples/hub-pages/account.njk
  docs/examples/hub-pages/example.njk
  docs/examples/hub-pages/messages.njk
  docs/examples/hub-pages/services.njk
  docs/examples/hub-pages/your-health.njk
  docs/patterns/confirmation-page.md
  docs/patterns/error-page.md
  docs/patterns/hub-page.md
Labels: documentation, pattern

#278 Restructure 'Get started' side nav + update page names
  docs/_includes/layouts/community.njk
  docs/_includes/layouts/get-started.njk
  docs/community/help-and-feedback.md
  docs/community/share-findings.md
  docs/community/suggest-a-change.md
  docs/get-started/github-and-heroku.md
  docs/get-started/nhsapp-frontend.md
  docs/get-started/nhsapp-prototype.md
Labels: documentation

#289 Add warning button example
  docs/components/buttons.md
  docs/examples/buttons/button-warning.njk
Labels: component

#290 Update Figma links
  docs/_includes/example.njk
  docs/_includes/layouts/example.njk
  docs/components/icons.md
  docs/examples/badges/badge-large-9.njk
  docs/examples/badges/badge-large.njk
  docs/examples/badges/badge-small.njk
  docs/examples/panel/panel-heading-only.njk
  docs/examples/panel/panel-with-ref.njk
Labels: documentation

#269 Add secondary card link guidance and examples
  CHANGELOG.md
  docs/components/card-links.md
  docs/examples/cards/card-link-secondary-stacked.njk
  docs/examples/cards/card-link-secondary.njk
  docs/examples/problem-with-service/example.njk
  src/components/card/_card.scss
Labels: documentation, component, ready to review

#277 Fix secondary button layout shift
  src/components/button/_index.scss
Labels: :bug: bug, component

#296 Update NHS App prototype guidance
  docs/get-started/nhsapp-prototype.md
Labels: documentation

#294 Updated the homepage to include a link to prototyping guidance.
  docs/assets/css/app.scss
  docs/index.njk
Labels: documentation

#276 Lowercase 'npm'
  docs/get-started/installing-with-npm.md
Labels: documentation
